<?php
if ( 'comments.php' == basename($_SERVER['SCRIPT_FILENAME']) )	die ( 'Please do not load this page directly. Thanks.' );?><div id="comments"><?php
if ( !empty($post->post_password) ) :
if ( $_COOKIE['wp-postpass_' . COOKIEHASH] != $post->post_password ) :
?><div class="nopassword"><?php _e( 'This post is protected. Enter the password to view any comments.','sandbox' ) ?></div></div><!-- .comments --><?php
return;	endif;endif;?><?php if ( !(!$comments & 'open' != $post->comment_status) ): ?><div class="post-model"><i class="fa fa-comments-o" aria-hidden="true"></i><?php echo $post->comment_count; ?> 条回应</div><?php endif; ?><?php if ( 'open' == $post->comment_status ) : ?><div id="respond" class="comment-respond"><?php
if (get_option("require_name_email")) {	$req_ph = 'placeholder="必填"';	} else {	$req_ph = 'placeholder="可选"';	}$cmt_face_arr = get_option('comment_face');	$cmt_face_imgs = '';	foreach ($cmt_face_arr as $face) {	switch ($face['type']) {	case 'p': $cmt_face_fmt = 'png'; break;	case 'g': $cmt_face_fmt = 'gif'; break;	}$cmt_face_imgs .= '<img src='.get_stylesheet_directory_uri().'/faces/'.$face['name'].'.'.$cmt_face_fmt.' @click="addCommentFace(\'[face '.$face['type'].'='.$face['name'].']\')">';	}?><el-popover ref="nickname" placement="bottom-start" width="275" v-model="comment.popover_nickname" transition="el-zoom-in-top"><el-form ref="form" label-width="45px"><el-form-item label="昵称" style="margin-bottom:0;"><el-input v-model="comment.name" size="small" type="text" name="name" <?php echo $req_ph; ?>></el-input></el-form-item><el-form-item label="邮箱" style="margin-bottom:0;"><el-input v-model="comment.email" size="small" type="email" name="email" <?php echo $req_ph; ?>></el-input></el-form-item><el-form-item label="网站" style="margin-bottom:0;"><el-input v-model="comment.url" size="small" type="url" name="homepage" placeholder="可选"></el-input></el-form-item></el-form></el-popover><el-popover ref="faces" placement="bottom-start" width="280" v-model="comment.popover_faces" transition="el-zoom-in-top"><div class="popover_faces"><?php echo $cmt_face_imgs; ?></div></el-popover><el-popover ref="validate" placement="top-end" width="190" v-model="comment.popover_validate" transition="el-zoom-in-top"><div style="margin: 5px 0;font-weight: bold;font-size:13px;">验证码</div><div style="margin-bottom: 5px">输入运算符及数字使等式成立</div>
{{comment.validate_num1}} <el-input v-model="comment.validate_input" size="mini" placeholder="符号+数字" style="display: inline-block;width: 80px;margin: 0 5px;"></el-input> = {{comment.validate_num2}}<div style="text-align: right;margin-top: 15px"><span style="float: left"><el-checkbox size="small" v-model="comment.ding" style='transform: scale(.79);'></el-checkbox> 点赞</span><el-button size="mini" type="text" @click="validate_random"><i class="fa fa-refresh" aria-hidden="true"></i></el-button><el-button size="mini" :plain="false" type="primary" @click="$('#submit-comment').trigger('click')">确定</el-button></div></el-popover><el-popover ref="logout" placement="bottom-start" v-model="comment.popover_logout" transition="el-zoom-in-top">
退出登录？
<div style="text-align: right;"><el-button size="mini" type="text" @click="comment.popover_logout=false">取消
</el-button><a href="<?php echo wp_logout_url( get_permalink() ); ?>" class="el-button el-button--primary el-button--mini">确定</a></div></el-popover><template><form action="<?php echo esc_url( home_url( '/' ) ); ?>wp-comments-post.php" method="post" id="commentform" class="comment-form clear-float"><div class="comment-form-comment"><textarea id="comment" name="comment" cols="10" rows="5" aria-required="true" placeholder="<?php echo get_option("comment_area_placeholder"); ?>" v-model="comment.text"></textarea></div><input id="author" name="author" type="hidden" v-model="comment.name"><input id="email" name="email" type="hidden" v-model="comment.email"><input id="url" name="url" type="hidden" v-model="comment.url"><input id="big_fa_ding" name="big_fa_ding" type="hidden" v-model="comment.ding"><input id="cmt_validate_num1" name="cmt_validate_num1" type="hidden" v-model="comment.validate_num1"><input id="cmt_validate_num2" name="cmt_validate_num2" type="hidden" v-model="comment.validate_num2"><input id="cmt_validate_input" name="cmt_validate_input" type="hidden" v-model="comment.validate_input"><p class="form-meta"><?php
if (get_option("comment_face")) {	echo '<a class="comment-meta faces" v-popover:faces></a> ';	}?><a class="comment-meta nick-name" v-popover:nickname v-show="!comment.is_user_logged_in">{{comment.name.replace(/ /g, '') != '' ? comment.name : '昵称'}}</a><span class="comment-meta nick-name" v-popover:logout v-show="comment.is_user_logged_in"><?php global $current_user;get_currentuserinfo();echo $current_user->user_login; ?></span></p><p class="form-submit"><?php echo get_cancel_comment_reply_link( '取消回复' ); ?><button name="submit" id="submit-comment" class="submit-comment" value="提交评论" class="submit" type="submit" @click="validateComment($event)" v-show="!comment.need_validate | comment.is_user_logged_in">提交评论</button><span class="submit-comment" value="提交评论" v-popover:validate v-show="comment.need_validate & !comment.is_user_logged_in">提交评论</span><?php
echo get_comment_id_fields( $post->id );	do_action( 'comment_form',$post->id );	?></p></form></template></div><?php endif
?><?php if ( !(!$comments & 'open' != $post->comment_status) ) : ?><div id="comments-list" class="comments"><ol class="commentlist"><?php wp_list_comments( 'type=comment&callback=mytheme_comment' ); ?></ol><?php
if (get_option('page_comments')) {
$comment_pages = paginate_comments_links('echo=0');if ($comment_pages) {	?><div id="commentnavi"><?php echo $comment_pages; ?></div><?php
}}?></div><?php endif; ?></div><!-- #comments -->
